#!/usr/xbin/bash

k="\033[33;1m"
 m="\033[31;1m"
  pu="\033[39;1m"
   p="\033[36;1m"
    b="\033[34;1m"
     h="\033[32;1m"
      c="\033[35;1m"
       JAM=`date +%H`
        MENIT=`date +%M`
         DETIK=`date +%S`
         TANGGAL=`date +%d`
        BULAN=`date +%m`
      TAHUN=`date +%Y`
mp="\033[41;1;39m"
o="\033[0m"
clear

printf "\n    ${p}─╤╦︻${h}=${p}(${m}◣${k}_${m}◢${p})${h}=${p}︻╦╤─         ${m}[ ${pu}WELCOME ${m}]\n"		
printf "       ${h}   __${b}H${h}__           ${m}[ ${pu}GEMUDI TERMUX ${m}]\n"
printf "${p}           [${m}'${p}] ${p}  ___   ___   __  __   _   _   ___    _ \n"
printf "${p}           [${m}'${p}] ${p} / __| | __| |  \/  | | | | | |   \  (_)\n"
printf "${p}           [${m}'${p}] ${p}| (_ | | _|  | |\/| | | |_| | | |) | | |\n"
printf "${p}           [${m}'${p}] ${p} \___| |___| |_|  |_|  \___/  |___/  |_|\n"
printf "${h}            V                ${m}[ ${pu}$TANGGAL-$BULAN-$TAHUN ${m}]\n"
printf "${pu}    ▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n\n"

export PS1='\[\033[01;39m\][ \[\033[01;35m\]${PWD/*\//}\[\033[01;39m\] ]\[\033[01;31m\]•\[\033[01;32m\]>\[\033[01;39m\] '
